#ALGPHELLO

# mt6737 platform boardconfig
DEVICE_PATH := device/samsung/grandpplte

#ALGPHELLO

# Platform
TARGET_BOARD_PLATFORM := mt6735
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := mt6737t
TARGET_NO_FACTORYIMAGE := true
TARGET_BOARD_PLATFORM_GPU := mali-t720mp2
MTK_GPU_VERSION := mali midgard m7p0

# Architecture
FORCE_32_BIT := true
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_CORTEX_A53 := true
TARGET_CPU_SMP := true

# Display
TARGET_SCREEN_HEIGHT := 960
TARGET_SCREEN_WIDTH := 540

# Filesystem
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs

# Use MKE2FS for creating ext4 images
TARGET_USES_MKE2FS := true

#ALGPHELLO

# Kernel

BOARD_KERNEL_BASE := 0x3fffc000
BOARD_KERNEL_PAGESIZE := 0x00000800
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x04004000
BOARD_SECOND_OFFSET := 0x00f04000
BOARD_TAGS_OFFSET := 0x0e004000
BOARD_DT_SIZE := 0x00076800
TARGET_KERNEL_ARCH := arm
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,32N2 androidboot.selinux=permissive

BOARD_MKBOOTIMG_ARGS := --base $(BOARD_KERNEL_BASE) --pagesize $(BOARD_KERNEL_PAGESIZE) --kernel_offset $(BOARD_KERNEL_OFFSET) --ramdisk_offset $(BOARD_RAMDISK_OFFSET) --second_offset $(BOARD_SECOND_OFFSET) --tags_offset $(BOARD_TAGS_OFFSET) --dt dt.img --board $(TARGET_BOARD_PLATFORM)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
#ALGPHELLO

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE      := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE 	:= 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE 	:= 3229614080
BOARD_USERDATAIMAGE_PARTITION_SIZE 	:= 3900702720
BOARD_CACHEIMAGE_PARTITION_SIZE 	:= 419430400
BOARD_FLASH_BLOCK_SIZE := 4096

# Recovery
BOARD_HAS_NO_SELECT_BUTTON := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/fstab.mt6735

# System Properties
TARGET_SYSTEM_PROP := $(DEVICE_PATH)/system.prop

# Hack for building without kernel sources
$(shell mkdir -p $(OUT)/obj/KERNEL_OBJ/usr)

#ALGPHELLO
